### ISSUE TITLE
PeerJ R2C9a

### ISSUE THREAD

**Issue by danielskatz** [openjournals/paper-JOSS-oneyear#32]
> Section 3
> 
> It is unclear whether JOSS also checks whether the software is original, in the sense that it doesn’t re-invent a wheel. One of the goals of peer reviews of scientific papers is that the author is the first one to discover a result and puts a time stamp on it (see above). Does the journal allow any research software or does it help to avoid re-inventing the wheel? I miss this aspect about originality (see also section 4 on review criteria where it seems to be hidden in statement of need).
>

**Comment by danielskatz** [comment]
I don't think we care about this to a large extent, as I mentioned in #22 )

**Comment by cMadan** [comment]
I agree, we aren't selecting for novelty/originality here

**Comment by kyleniemeyer** [comment]
I agree that in general we aren't selecting for originality or potential impact, but technically one of our submission criteria is this: 
> Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)

so our response should mention this.

**Comment by kyleniemeyer** [comment]
Here is my suggested response:
> As we have clarified, the primary goal of JOSS is to provide credit to developers of research software for their efforts via a citable article.
>
>While we do not generally select\slash review for originality or potential impact, one of our submission requirements is that the software ``should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)''; this is described on page 5 of the article.

@arfon @danielskatz @cMadan think this is good now?

**Comment by arfon** [comment]
> @arfon @danielskatz @cMadan think this is good now?

👍

**Comment by danielskatz** [comment]
I'm not sure I agree with this as written.

If software X does something well, and software Y is written to do the same thing, perhaps just about equally well, we want people to be able to cite either software, not just the first one.

**Comment by danielskatz** [comment]
I would have liked to have reopened this but don't seem to have permission

**Comment by kyleniemeyer** [comment]
@danielskatz sure, I was just going off what our current submission requirements are...  I can just remove that bit from the response, though.

**Comment by kyleniemeyer** [comment]
How about just 
> As we have clarified, the primary goal of JOSS is to provide credit to developers of research software for their efforts via a citable article. Thus, we do not generally select/review for originality or potential impact, but instead whether software meets our standards.

**Comment by danielskatz** [comment]
I like that.

**Comment by kyleniemeyer** [comment]
@danielskatz 👍
