### ISSUE TITLE
PeerJ R2C9b

### ISSUE THREAD

**Issue by danielskatz** [openjournals/paper-JOSS-oneyear#33]
> Section 3
> 
> This section is a bit unclear on what is actually the target. On the one hand it is ‘ just’ advertising, on the other hand it mentions detailed code review.
> 
> If only high level functioning is reviewed, what is there actually to review in JOSS. How is quality and originality defined? So, how to determine impact and quality as peer review of scientific papers generally does? Does the code review have this role? Does this include coding standards, bench marking, checking for correctness of scientific result (in addition to code tests).

**Comment by danielskatz** [comment]
see #26

**Comment by kyleniemeyer** [comment]
How's this? 

>The goal of peer review in JOSS is not to judge submissions for acceptance or rejection, but rather to bring the submission to an acceptable standard. Any submission that meets our standards should be accepted, as we do not filter based on potential impact or quality (beyond that implied by meeting our standards). The peer review encompasses the code, software functionality, tests, and any associated artifacts (documentation, examples, etc.). We have added a sentence to page 5 clarifying the target of peer review.


I've also added a sentence to the Open Peer Review section on page 5:
> The actual review includes the code, software functionality/performance claims, test suite (if present), documentation, and any other material associated with the software.

**Comment by arfon** [comment]
👍 LGTM
