### ISSUE TITLE
cMadan's affiliation

### ISSUE THREAD

**Issue by cMadan** [openjournals/paper-JOSS-oneyear#34]
Could you also update my affiliation? It was filled correctly in the manuscript submission website, but the one in the tex is out-of-date.

Old:
`\affil[8]{Department of Psychology, Boston College, Chestnut Hill, MA, USA}`

Updated:
`\affil[8]{School of Psychology, University of Nottingham, Nottingham, United Kingdom}`

Thanks!

**Comment by kyleniemeyer** [comment]
fixed!
